version: 2.1
jobs:
  build:
    macos:
      xcode: "11.1.0"

    steps:
      - checkout

      - run:
          name: "Install tooling"
          command: brew install swiftlint maven gmp

      - run:
          name: "Install Poetry"
          command: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

      - run:
          name: "Run Node SDK Demo"
          command: cd node && npm i && node src/index-xrp.js

      - run:
          name: "Run Node ILP SDK Demo"
          command: cd node && npm i && node src/index-ilp.js

      - run:
          name: "Run Swift SDK Demo"
          command: cd swift && carthage bootstrap --platform mac && set -o pipefail && xcodebuild build -scheme Demo ONLY_ACTIVE_ARCH=YES

      - run:
          name: "Run Swift ILP SDK Demo"
          command: cd swift/ILP && carthage bootstrap --platform mac && set -o pipefail && xcodebuild build -scheme Demo ONLY_ACTIVE_ARCH=YES

      - run:
          name: "Run Java SDK Demo"
          command: cd java && mvn package && mvn exec:java@xrp

      - run:
          name: "Run Java ILP SDK Demo"
          command: cd java && mvn package && mvn exec:java@ilp

      - run:
          name: "Run Python SDK Demo"
          command: cd python && poetry install && poetry run python main.py
